name: ng2-dart-boilerplate
version: 0.0.1
description: >
  Boilerplate for Angular2 Dart
author: Louis Laagland <louis@wunderful.nl>
environment:
  sdk: '>=1.12.0 <2.0.0'
dependencies:
  browser: '^0.10.0+2'
  angular2: '^2.0.0-alpha.53'
dev_dependencies:
  test: '>=0.6.0 <0.13.0'
transformers:
- angular2:
    entry_points: web/main.dart
- $dart2js:
    environment:
      PROD: "true"